# Generated by Django 4.2.1 on 2023-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("experience_date", models.DateTimeField()),
                ("done", models.BooleanField(default=False)),
                (
                    "tags",
                    models.ManyToManyField(related_name="tags", to="todo_list.tag"),
                ),
            ],
        ),
    ]
