# Generated by Django 4.2.1 on 2023-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="experience_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
